### ISSUE TITLE
Is this Available on Linux?

### ISSUE THREAD

**Issue by Ezharjan** [masskro0/Urban-Test-Generator-Fuel-Scoring-Function#11]
Is the result mentioned in this repository reproducible on Linux OS?

**Comment by masskro0** [comment]
Since BeamNG.research is only supported on Windows, I doubt that you can reproduce the results on Linux. There is some work in progress to port BeamNG.research natively to Linux, but at the moment, the implementation is in the experimental state and the sensors are not properly working. See the following issues for reference:
https://github.com/BeamNG/BeamNGpy/issues/198
https://github.com/BeamNG/BeamNGpy/issues/79

**Comment by Ezharjan** [comment]
> Since BeamNG.research is only supported on Windows, I doubt that you can reproduce the results on Linux. There is some work in progress to port BeamNG.research natively to Linux, but at the moment, the implementation is in the experimental state and the sensors are not properly working. See the following issues for reference: [BeamNG/BeamNGpy#198](https://github.com/BeamNG/BeamNGpy/issues/198) [BeamNG/BeamNGpy#79](https://github.com/BeamNG/BeamNGpy/issues/79)

Thanks~
